=== dvaneynde/elm-domotics-ui/DiamondBoardsConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dlvmechanografie.eu/DiamondBoardsConfig"
	xmlns:tns="http://dlvmechanografie.eu/DiamondBoardsConfig"
	elementFormDefault="qualified">

	<element name="boards">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<choice>
					<element name="opalmm" type="tns:opalmmType" />
					<element name="dmmat" type="tns:dmmatType" />
				</choice>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="boardStruct" abstract="true">
		<attribute name="board" type="int" use="required" />
		<attribute name="address" type="string" use="required" />
		<attribute name="desc" type="string" />
	</complexType>
	<complexType name="boardChannelStruct">
		<attribute name="channel" type="int" use="required" />
		<attribute name="logical-id" type="int" use="required" />
	</complexType>
	<complexType name="channel1to8Struct">
		<sequence minOccurs="1" maxOccurs="8">
			<element name="channel" type="tns:boardChannelStruct" />
		</sequence>
	</complexType>
	<complexType name="channel1to2Struct">
		<sequence minOccurs="1" maxOccurs="2">
			<element name="channel" type="tns:boardChannelStruct" />
		</sequence>
	</complexType>

	<complexType name="opalmmType">
		<complexContent>
			<extension base="tns:boardStruct">
				<sequence>
					<element name="digital-input" type="tns:channel1to8Struct"
						minOccurs="0" />
					<element name="digital-output" type="tns:channel1to8Struct"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="dmmatType">
		<complexContent>
			<extension base="tns:boardStruct">
				<sequence>
					<element name="analog-input" type="tns:channel1to2Struct"
						minOccurs="0" />
					<element name="analog-output" type="tns:channel1to2Struct"
						minOccurs="0" />
					<element name="digital-input" type="tns:channel1to8Struct"
						minOccurs="0" />
					<element name="digital-output" type="tns:channel1to8Struct"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
</schema>

=== dvaneynde/elm-domotics-ui/src/test/resources/TestDiamondHwConfig1.xml
<?xml version="1.0" encoding="UTF-8"?>
<boards xmlns="http://dlvmechanografie.eu/DiamondBoardsConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DiamondBoardsConfig /Users/dirk/Documents/workspace_helios/domotic/DiamondBoardsConfig.xsd ">
	<opalmm address="0x380" board="0" desc="Een opalmm bordje.">
		<digital-input>
			<channel channel="5" logical-id="87" />
		</digital-input>
		<digital-output>
			<channel channel="2" logical-id="13" />
		</digital-output>
	</opalmm>
	<dmmat board="1" address="0x400" desc="First dmmatt board">
		<analog-output>
			<channel channel="0" logical-id="10" />
		</analog-output>
	</dmmat>

</boards>

=== dvaneynde/elm-domotics-ui/DiamondBoardsConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<boards xmlns="http://dlvmechanografie.eu/DiamondBoardsConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DiamondBoardsConfig DiamondBoardsConfig.xsd ">
	<opalmm board="0" address="0x300" desc="Board 0, opalmm.">
		<digital-input>
			<channel channel="0" logical-id="5" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="6" />
		</digital-output>
	</opalmm>
	<dmmat board="1" address="0x310" desc="Board 1, dmmatt.">
		<analog-input>
			<channel channel="0" logical-id="2" />
		</analog-input>
		<analog-output>
			<channel channel="0" logical-id="0" />
			<channel channel="1" logical-id="1" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="3" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="4" />
		</digital-output>
	</dmmat>
	<opmm1616 address="0x320" board="2" desc="Board 2, opmm1616.">
		<digital-input>
			<channel channel="0" logical-id="7" />
		</digital-input>
		<digital-output>
			<channel channel="1" logical-id="8" />
		</digital-output>
	</opmm1616>

</boards>
