=== dvaneynde/elm-domotics-ui/DomoticConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dlvmechanografie.eu/DomoticConfig"
	xmlns:tns="http://dlvmechanografie.eu/DomoticConfig" elementFormDefault="qualified">
	<element name="domotic">
		<complexType>
			<choice maxOccurs="unbounded">

				<element name="switch" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockWithChannelStruct">
								<attribute name="singleClick" type="boolean" default="true"/>
								<attribute name="longClick" type="boolean" default="false" />
								<attribute name="doubleClick" type="boolean" default="false" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="dimmerSwitches" type="tns:BlockWithChannelUpDownStruct"
					minOccurs="0" maxOccurs="1" />

				<element name="lamp" type="tns:blockWithChannelStruct" minOccurs="0"
					maxOccurs="1" />
				<element name="fan" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockWithChannelStruct">
								<attribute name="lamp" type="IDREF" use="optional" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="dimmedLamp" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockWithChannelStruct">
								<attribute name="fullOnHwOutput" type="int" use="required" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="screen" type="tns:BlockWithChannelUpDownStruct"
					minOccurs="0" maxOccurs="1" />


				<element name="switchboard" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockStruct">
								<sequence>
									<element name="connection" maxOccurs="unbounded">
										<complexType>
											<attribute name="switch" type="IDREF" use="required" />
											<attribute name="lamp" type="IDREF" use="required" />
											<attribute name="allOff" type="boolean" default="false" />
										</complexType>
									</element>
									<element name="allSwitch" type="tns:allSwitchStruct" minOccurs="0" />
								</sequence>
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="switchboardDimmer" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockStruct">
								<sequence>
									<element name="connection" maxOccurs="unbounded">
										<complexType>
											<attribute name="dimmerSwitch" type="IDREF" use="required" />
											<attribute name="dimmedLamp" type="IDREF" use="required" />
										</complexType>
									</element>
									<element name="allSwitch" type="tns:allSwitchStruct" minOccurs="0" />
								</sequence>
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="switchboardFans" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockStruct">
								<sequence>
									<element name="connection" maxOccurs="unbounded">
										<complexType>
											<attribute name="switch" type="IDREF" use="required" />
											<attribute name="fan" type="IDREF" use="required" />
										</complexType>
									</element>
								</sequence>
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="switchboardScreens" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:blockStruct">
								<sequence>
									<element name="connection" maxOccurs="unbounded">
										<complexType>
											<attribute name="switchDown" type="IDREF" use="required" />
											<attribute name="switchUp" type="IDREF" use="required" />
											<attribute name="screen" type="IDREF" use="required" />
										</complexType>
									</element>
									<element name="allUpDownSwitches" minOccurs="0">
										<complexType>
											<attribute name="allDownSwitch" type="IDREF" />
											<attribute name="allUpSwitch" type="IDREF" />
										</complexType>

									</element>
								</sequence>
							</extension>
						</complexContent>
					</complexType>
				</element>
			</choice>
		</complexType>
	</element>

	<complexType name="allSwitchStruct">
		<attribute name="switch" use="required" type="IDREF" />
		<attribute name="allOff" default="true" type="boolean" />
		<attribute name="allOn" default="false" type="boolean" />
	</complexType>
	<complexType name="blockStruct">
		<attribute name="name" use="required" type="ID" />
		<attribute name="desc" use="optional" type="string" />
	</complexType>
	<complexType name="blockWithChannelStruct">
		<complexContent>
			<extension base="tns:blockStruct">
				<annotation>
					<documentation>Default channel naam is name attribute, kan overridden door
						channel attribuut.
					</documentation>
				</annotation>
				<attribute name="channel" type="string" use="optional" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="BlockWithChannelUpDownStruct">
		<complexContent>
			<extension base="tns:blockStruct">
				<annotation>
					<documentation>Default channel naam is name attribute, kan overridden door
						channel attribuut.
					</documentation>
				</annotation>
				<attribute name="channelDown" type="string" use="optional" />
				<attribute name="channelUp" type="string" use="optional" />
			</extension>
		</complexContent>
	</complexType>

</schema>

=== dvaneynde/elm-domotics-ui/src/test/resources/TestDomoticConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<domotic xmlns="http://dlvmechanografie.eu/DomoticConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DomoticConfig ../../../DomoticConfig.xsd ">
	<switch channel="1" name="SchakLichtBadkamer0" desc="Licht badkamer gelijkvloers." />
	<switch channel="2" name="SchakLichtWC0" desc="Licht badkamer boven." />
	<switch channel="10" name="SchakFanBadkamer0" />
	<switch channel="11" name="SchakFanWC0" />
	<switch channel="5" name="AllOnOff" desc="Alle lichten aan/uit." />
	<switch name="SchakKeukenScreenNeer" channel="6" />
	<switch name="SchakKeukenScreenOp" channel="7" />
	<lamp channel="3" name="LichtBadkamer0" />
	<lamp channel="4" name="LichtWC0" />
	<fan name="FanBadkamer0" channel="6" />
	<fan name="FanWC0" channel="7" lamp="LichtWC0" desc="Ventilator WC gelijkvloers." />
	<screen name="SchermKeuken" channelDown="23" channelUp="15" />
	<switchboard name="sb" desc="Algemeen schakelbord">
		<connection switch="SchakLichtBadkamer0" lamp="LichtBadkamer0" />
		<connection switch="SchakLichtWC0" lamp="LichtBadkamer0" />
		<allSwitch switch="AllOnOff" allOff="true" allOn="true" />
	</switchboard>
	<switchboardFans name="sbfans">
		<connection switch="SchakFanWC0" fan="FanWC0" />
		<connection switch="SchakFanBadkamer0" fan="FanBadkamer0" />
	</switchboardFans>
	<switchboardScreens name="sbscreens">
		<connection screen="SchermKeuken" switchDown="SchakKeukenScreenNeer"
			switchUp="SchakKeukenScreenOp" />
	</switchboardScreens>
</domotic>
